import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

import Footer from "@/components/Footer";
import BackgroundOverlay from "@/components/BackgroundOverlay";
import NavigationHeader from "@/components/NavigationHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${dmSans.variable}`}
    >



      <body className="min-h-screen text-foreground antialiased">
        {/* Navigation Header */}
        <NavigationHeader />

        {/* Background Overlay */}
        <BackgroundOverlay />

        {children}
        
        <Footer />
      </body>

    </html>
  );
}
